apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    k8s-app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ollama
  template:
    metadata:
      labels:
        k8s-app: ollama
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/csu-tide
                operator: Exists
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A100-80GB-PCIe
      containers:
      - name: pod-ollama
        image: "ollama/ollama:0.1.24"
        ports:
          - containerPort: 11434
        resources:
          limits:
            memory: 64Gi
            cpu: 16
            nvidia.com/gpu: 1
          requests:
            memory: 32Gi
            cpu: 8
            nvidia.com/gpu: 1
        command: ["ollama", "serve"]
        volumeMounts:
        - name: pvc-ollama
          mountPath: /root/.ollama
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/sdsu-fix
        operator: Exists
      - effect: NoSchedule
        key: nautilus.io/csu-tide
        operator: Exists
      volumes:
      - name: pvc-ollama
        persistentVolumeClaim:
          claimName: ollama

apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    k8s-app: ollama
  ports:
  - protocol: TCP
    port: 80
    targetPort: 11434
  type: ClusterIP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
    ingress.kubernetes.io/allowlist-source-range: "130.191.0.0/16, 146.244.0.0/16"
  name: ollama-ingress
spec:
  rules:
  - host: sdsu-aicenter-ollama.nrp-nautilus.io
    http:
      paths:
      - backend:
          service:
            name: ollama-service
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - sdsu-aicenter-ollama.nrp-nautilus.io
